#!/usr/bin/env bash
# Bootstrap a fresh Debian (12+) VPS to run OpenKeepr.
#
# Run as root, ideally on a freshly provisioned server. Idempotent — safe to
# re-run; existing files are left alone unless --force is passed.
#
# Usage:
#   sudo bash scripts/install_vps.sh <hostname> <admin-email> [--copy-ssh-keys] [--repo-url URL]
#
# Examples:
#   sudo bash scripts/install_vps.sh openkeepr.example.com you@example.com
#   sudo bash scripts/install_vps.sh openkeepr.example.com you@example.com --copy-ssh-keys
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root (use sudo)." >&2
    exit 1
fi

HOST="${1:?usage: install_vps.sh <hostname> <admin-email> [--copy-ssh-keys]}"
ADMIN_EMAIL="${2:?usage: install_vps.sh <hostname> <admin-email> [--copy-ssh-keys]}"
shift 2
COPY_SSH=0
REPO_URL="${OPENKEEPR_REPO_URL:-https://github.com/OWNER/openkeepr.git}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --copy-ssh-keys) COPY_SSH=1 ;;
        --repo-url) REPO_URL="$2"; shift ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
    shift
done

APP_USER="openkeepr"
APP_HOME="/home/${APP_USER}"
APP_DIR="${APP_HOME}/app"
ENV_FILE="${APP_DIR}/.env"

say() { printf "\n\033[1;36m==> %s\033[0m\n" "$*"; }

say "Installing system packages…"
apt-get update -y
apt-get install -y --no-install-recommends \
    python3 python3-venv python3-pip git nginx ca-certificates curl \
    fail2ban ufw certbot python3-certbot-nginx sqlite3 sudo

say "Creating ${APP_USER} user…"
if ! id -u "$APP_USER" >/dev/null 2>&1; then
    useradd \
        --create-home \
        --home-dir "$APP_HOME" \
        --shell /bin/bash \
        --comment "OpenKeepr service account" \
        "$APP_USER"
fi
# Ensure the home folder exists & has the right ownership (in case of re-run)
install -d -o "$APP_USER" -g "$APP_USER" -m 0755 "$APP_HOME"

if [[ $COPY_SSH -eq 1 ]]; then
    say "Copying SSH keys from /root/.ssh to ${APP_HOME}/.ssh…"
    if [[ -f /root/.ssh/authorized_keys ]]; then
        install -d -o "$APP_USER" -g "$APP_USER" -m 0700 "${APP_HOME}/.ssh"
        cp /root/.ssh/authorized_keys "${APP_HOME}/.ssh/authorized_keys"
        chown "$APP_USER:$APP_USER" "${APP_HOME}/.ssh/authorized_keys"
        chmod 0600 "${APP_HOME}/.ssh/authorized_keys"
        echo "  → SSH keys copied. You can now SSH as: ${APP_USER}@${HOST}"
    else
        echo "  → /root/.ssh/authorized_keys not found — skipping."
    fi
fi

say "Cloning / updating the application into ${APP_DIR}…"
if [[ ! -d "${APP_DIR}/.git" ]]; then
    sudo -u "$APP_USER" git clone "$REPO_URL" "$APP_DIR"
else
    sudo -u "$APP_USER" git -C "$APP_DIR" pull --ff-only
fi

say "Creating virtualenv & installing requirements…"
sudo -u "$APP_USER" python3 -m venv "${APP_DIR}/.venv"
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/pip" install --upgrade pip
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/pip" install -r "${APP_DIR}/requirements.txt"

say "Writing ${ENV_FILE} (only if missing)…"
if [[ ! -f "$ENV_FILE" ]]; then
    gen() { python3 -c "import secrets;print(secrets.token_urlsafe(64))"; }
    cat > "$ENV_FILE" <<EOF
# Generated by install_vps.sh on $(date -u +%FT%TZ)
APP_NAME=OpenKeepr
FLASK_ENV=production
DEBUG=false
HOST=127.0.0.1
PORT=5000
BASE_URL=https://${HOST}
SECRET_KEY=$(gen)
RECIPIENT_HASH_SECRET=$(gen)
SERVER_ENCRYPTION_KEY=$(gen)
DATABASE_URL=sqlite:///openkeepr.db
SESSION_COOKIE_SECURE=true
PREFERRED_URL_SCHEME=https
ALLOWED_HOSTS=${HOST}
PROXY_FIX_HOPS=1
MAIL_ENABLED=false
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_LOGIN_PATH=/admin-login
SECURITY_CONTACT=mailto:${ADMIN_EMAIL}
LOG_LEVEL=INFO
LOG_FILE=
EOF
    chmod 0640 "$ENV_FILE"
    chown "$APP_USER":"$APP_USER" "$ENV_FILE"
    echo "  → Default .env created. Edit it to customise (then restart the service)."
else
    echo "  → .env already exists, leaving untouched."
fi

say "Initialising database & translations on first boot…"
# Run once to let the app create the schema / extract translations
sudo -u "$APP_USER" bash -c "set -a; source ${ENV_FILE}; set +a; cd ${APP_DIR} && .venv/bin/python -c 'from app import create_app; create_app()'"

say "Fetching offline assets (Bootstrap, marked, DOMPurify, …)…"
sudo -u "$APP_USER" "${APP_DIR}/.venv/bin/python" "${APP_DIR}/scripts/fetch_assets.py"

say "Installing systemd unit…"
install -m 0644 "${APP_DIR}/deploy/openkeepr.service" /etc/systemd/system/openkeepr.service
systemctl daemon-reload
systemctl enable --now openkeepr

say "Installing sudoers rule (lets the ${APP_USER} user manage its own service)…"
install -m 0440 "${APP_DIR}/deploy/openkeepr.sudoers" /etc/sudoers.d/openkeepr
visudo -c >/dev/null

say "Installing /usr/local/bin/openkeepr helper script…"
install -m 0755 "${APP_DIR}/deploy/openkeepr-ctl.sh" /usr/local/bin/openkeepr

say "Installing nginx site…"
sed "s/openkeepr.example.com/${HOST}/g" "${APP_DIR}/deploy/nginx.conf.example" \
    > /etc/nginx/sites-available/openkeepr.conf
ln -sf /etc/nginx/sites-available/openkeepr.conf /etc/nginx/sites-enabled/openkeepr.conf
# Some Debian default sites snare the default_server slot — leave them, just verify config
nginx -t

say "Requesting Let's Encrypt certificate (will reload nginx on success)…"
certbot --nginx -n --agree-tos -m "$ADMIN_EMAIL" -d "$HOST" || \
    echo "  → certbot failed (DNS not pointing here yet?). Re-run later: certbot --nginx -d ${HOST}"
systemctl reload nginx || true

say "Configuring fail2ban (basic nginx jail)…"
cat > /etc/fail2ban/jail.d/openkeepr.local <<'EOF'
[openkeepr-auth]
enabled = true
filter = nginx-limit-req
port = http,https
logpath = /var/log/nginx/access.log
maxretry = 10
findtime = 600
bantime = 3600
EOF
systemctl restart fail2ban || true

cat <<MSG

================================================================
  OpenKeepr is installed and running.

  URL:        https://${HOST}/
  Admin user: ${ADMIN_EMAIL}

  The initial admin password is printed once in the service log:
    sudo journalctl -u openkeepr -n 100 --no-pager | grep -A2 'password:'

  Managing the service:
    openkeepr status        # show systemd status
    openkeepr restart       # restart workers
    openkeepr logs          # tail the journal
    openkeepr stop / start  # stop / start

  SSH as the openkeepr user (if keys were copied):
    ssh ${APP_USER}@${HOST}

  IMPORTANT NEXT STEPS:
   1. Log in immediately and enable 2FA on your admin account.
   2. Edit ${ENV_FILE} for SMTP, branding, etc., then:
        openkeepr restart
   3. Configure off-host backups for ${APP_DIR}/instance/openkeepr.db
================================================================
MSG
